---
title: "Overview Vignette for CancerCellLineModelling Package"
author: "Phil Chapman"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_vignette: 
    toc: true
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo=FALSE, message=FALSE}
library(CancerCellLineModelling)
library(dplyr)
```

## Introduction
Intro - aim of package.  See CancerCellLines package on github

## Univariate analysis
Builds from the `makeRespVsGeneticDataFrame` function output.  Simple to use:

```{r}

con <- setupSQLite('~/BigData/CellLineData/CancerCellLines.db')
genelist <- c('BRAF', 'TP53', 'PTEN', 'NRAS', 'DGAT1')
drugs <- c('PLX4720', 'Nutlin-3', 'AZD6244')
cell_lines <- src_sqlite(con@dbname) %>% tbl('ccle_drug_data') %>% filter(Compound %in% drugs) %>% select(CCLE_name) %>%     distinct() %>% collect() %>% as.data.frame

my_df <-  makeRespVsGeneticDataFrame(con, 
                                     genelist, 
                                     cell_lines$CCLE_name, 
                                     drug = drugs, 
                                     data_types=c('cosmicclp', 'hybcap'), 
                                     drug_df=NULL)
mutcounts_df <- univariateAnalysisMutCounts(my_df)
res_df <- univariateAnalysis(my_df)
res_df <- univariateAnalysisFDR(res_df, 2)
univariateVolcanoPlot(res_df)

#a bigger example
library(piano)
genelist2 <- unlist(loadGSC('/Users/pchapman/BigData/GSEA/c5.bp.v5.0.symbols.gmt')$gsc['DNA_REPAIR'])
genelist2 <- c(genelist, genelist2)
my_df2 <- makeRespVsGeneticDataFrame(con, 
                             genelist2, 
                             cell_lines$CCLE_name, 
                             drug = drugs, 
                             data_types=c('cosmicclp', 'hybcap'), 
                             drug_df=NULL)

res_df2 <- univariateAnalysis(my_df2)
res_df2 <- univariateAnalysisFDR(res_df2, 2)
univariateVolcanoPlot(res_df2)
pp <- univariateVolcanoPlot(res_df2, use_fdr = TRUE)
pp
pp + ggplot2::scale_x_log10(limits=c(0.01, 100))

#shiny app
con <- setupSQLite('~/BigData/CellLineData/CancerCellLines.db')
msigdb <- loadGSC('/Users/pchapman/BigData/GSEA/msigdb.v5.0.symbols.gmt')
shinyUnivariateAnalysisApp(con)  #basic example with manually entered gene names
shinyUnivariateAnalysisApp(con, gsc=msigdb) #bigger example with all gene sets
shinyUnivariateAnalysisApp(con, drug_df = dietlein_data, gsc=msigdb) #custom example with all gene sets

#multivariate example
con <- setupSQLite('~/BigData/CellLineData/CancerCellLines.db')
my_df3 <- makeTallDataFrame(con, 
                             genelist2[1:30], 
                             cell_lines$CCLE_name, 
                             drug = drugs, 
                             data_types=c('affy', 'hybcap', 'resp'), 
                             drug_df=NULL)

test_df <- multivariateAnalysisPrep(my_df3, 'AZD6244')
glmnet_res <- multivariateAnalysisElasticNet(my_df3, 'AZD6244')
multivariateAnalysisVarImp(glmnet_res)
multivariateAnalysisVarImpPlot(glmnet_res, 20)

gbmfit_res <- multivariateAnalysisGBM(my_df3, 'AZD6244')
multivariateAnalysisVarImp(gbmfit_res)
multivariateAnalysisVarImpPlot(gbmfit_res, 20)

```



